const businesses=[{name:'Sharma Manufacturing',category:'Manufacturing',location:'Bhopal, MP',need:'Distributors',emoji:'🏭'},{name:'FastTrack Distributors',category:'Distribution',location:'Indore, MP',need:'Manufacturers',emoji:'🚚'},{name:'CityMart Retail',category:'Retail',location:'Bhopal, MP',need:'Suppliers',emoji:'🏪'},{name:'GreenFarm Foods',category:'Food & Agriculture',location:'Sehore, MP',need:'Retail partners',emoji:'🌾'},{name:'TechCraft Solutions',category:'Technology',location:'Indore, MP',need:'Business clients',emoji:'💻'},{name:'Aarav Logistics',category:'Logistics',location:'Bhopal, MP',need:'Business contracts',emoji:'📦'}];
const $=s=>document.querySelector(s),grid=$('#businessGrid'),search=$('#search'),category=$('#category');
function render(){const q=search.value.toLowerCase(),c=category.value,list=businesses.filter(b=>(!q||[b.name,b.category,b.location,b.need].join(' ').toLowerCase().includes(q))&&(!c||b.category===c));grid.innerHTML=list.map(b=>`<article class="biz"><div class="bizicon">${b.emoji}</div><div><h3>${b.name}</h3><p>${b.category} · ${b.location}</p><span>Looking for: ${b.need}</span></div><button class="connect" onclick="connect('${b.name}')">Connect</button></article>`).join('')||'<div class="empty">No matching businesses found.</div>'}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')}
function connect(name){openModal(`Connect with ${name}`,`<p>Send a business enquiry to <b>${name}</b>.</p><textarea id="enquiry" placeholder="Introduce your business and what you want to discuss..."></textarea><button class="btn primary" onclick="sendEnquiry('${name}')">Send Enquiry</button>`)}
function sendEnquiry(name){const text=$('#enquiry').value.trim();if(!text)return alert('Please write an enquiry first.');const data=JSON.parse(localStorage.getItem('ksEnquiries')||'[]');data.unshift({to:name,message:text,status:'Sent',date:new Date().toLocaleDateString()});localStorage.setItem('ksEnquiries',JSON.stringify(data));openModal('Enquiry sent','<p class="success">✓ Your enquiry has been added to your business activity.</p><button class="btn primary" onclick="closeModal()">Done</button>')}
function openSignup(){openModal('Create your business account',`<input id="bizName" class="field" placeholder="Business name"><input id="bizEmail" class="field" placeholder="Business email"><input id="bizCategory" class="field" placeholder="Industry"><input id="bizLocation" class="field" placeholder="City / State"><button class="btn primary" onclick="saveProfile()">Create Business Profile</button>`)}
function saveProfile(){const name=$('#bizName').value.trim();if(!name)return alert('Business name is required.');const profile={name,email:$('#bizEmail').value.trim(),category:$('#bizCategory').value.trim(),location:$('#bizLocation').value.trim()};localStorage.setItem('kharaSaudaProfile',JSON.stringify(profile));openModal('Business profile created','<p class="success">✓ Your profile is saved on this device for this MVP.</p><button class="btn primary" onclick="showDashboard()">Open Dashboard</button>')}
function showDashboard(){const p=JSON.parse(localStorage.getItem('kharaSaudaProfile')||'{}'),e=JSON.parse(localStorage.getItem('ksEnquiries')||'[]'),d=JSON.parse(localStorage.getItem('ksDeals')||'[]');openModal('My Business Dashboard',`<div class="dash"><h3>${p.name||'My Business'}</h3><p>${p.category||'Business'} · ${p.location||'Location not added'}</p><div class="dashstats"><b>${e.length}<small>Enquiries</small></b><b>${d.filter(x=>x.status!=='Completed').length}<small>Active deals</small></b><b>${d.length}<small>Total deals</small></b></div><h4>Recent enquiries</h4>${e.slice(0,3).map(x=>`<p>📩 <b>${x.to}</b> — ${x.status}</p>`).join('')||'<p>No enquiries yet.</p>'}<button class="btn primary" onclick="createDeal()">Create Deal</button></div>`)}
function createDeal(){const e=JSON.parse(localStorage.getItem('ksEnquiries')||'[]');if(!e.length)return openModal('No enquiry yet','<p>Connect with a business first, then create a deal.</p>');const name=e[0].to;openModal('Create Deal',`<p>Deal with <b>${name}</b></p><input id="dealTitle" class="field" placeholder="Deal / order title"><input id="dealValue" class="field" placeholder="Estimated value (₹)"><select id="dealStatus" class="field"><option>Enquiry</option><option>Negotiation</option><option>Confirmed</option><option>Completed</option></select><button class="btn primary" onclick="saveDeal('${name}')">Save Deal</button>`)}
function saveDeal(name){const title=$('#dealTitle').value.trim();if(!title)return alert('Deal title is required.');const d=JSON.parse(localStorage.getItem('ksDeals')||'[]');d.unshift({with:name,title,value:$('#dealValue').value,status:$('#dealStatus').value,date:new Date().toLocaleDateString()});localStorage.setItem('ksDeals',JSON.stringify(d));openModal('Deal created','<p class="success">✓ Deal saved. The production version will sync it with the other business.</p><button class="btn primary" onclick="closeModal()">Done</button>')}
function closeModal(){$('#modal').classList.remove('show')}
search.addEventListener('input',render);category.addEventListener('change',render);render();